### ISSUE TITLE
SevPatches using ~27000 µs/t

### ISSUE THREAD

**Issue by bastetfurry** [DarkPacks/SevPatches#1]
While investigating lag on our server i found SevPatches to be a huge resource user.
Is that normal or something to look into?

![2021-04-16_20 00 45](https://user-images.githubusercontent.com/3686292/115065649-ad30e580-9eee-11eb-8279-088be2fc16b4.png)

**Comment by sam-kirby** [comment]
This is probably due to a very silly mistake on my part, fixed in b4d07c9 - update to SevPatches 1.8 or restart the server more frequently.

**Comment by bastetfurry** [comment]
Is it enough to update on the server or would the clients need that update also? 
And thanks for the fast response. :cat:

**Comment by sam-kirby** [comment]
In theory it's fine to just update the server, in practice Forge might complain about the version mismatch. If possible, can you try it? If it doesn't work let me know and I'll make a build that won't require a client update.

**Comment by bastetfurry** [comment]
```
[20:49:01] [Netty Epoll Server IO #2/ERROR] [FML]: Network Disconnect: Server Mod rejections:
SevPatches: Requires version 1.8 but client has 1.6.
```

Nope, would need the clients to update too

**Comment by sam-kirby** [comment]
Okay, I'll get back to you later this evening with a build that won't require it.

**Comment by sam-kirby** [comment]
https://s3.eu-west-2.amazonaws.com/share.misc/sevpatches-1.8-SNAPSHOT.jar

This should work - please make sure you delete old versions of the mod.

**Comment by bastetfurry** [comment]
Thanks, i have that version running now. If the problem still persists i come back to you.
Nice weekend! :)
